### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [julianbruegger/corona-display#2]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest released the code under the GPLv3 or AGPLv3 license so that others are encouraged to contribute changes back to your project.

**Comment by julianbruegger** [comment]
created and added a LICENCE

Thanks for the Input @TechnologyClassroom

**Comment by TechnologyClassroom** [comment]
Excellent choice!

https://www.gnu.org/licenses/gpl-howto.en.html
