### ISSUE TITLE
country = soup_w.select('h1')[0].text.strip() IndexError: list index out of range

### ISSUE THREAD

**Issue by wmenesw** [julianbruegger/corona-display#6]
I wanted to run your code but I faced an error. How can i solve?

country = soup_w.select('h1')[0].text.strip()
IndexError: list index out of range

**Comment by julianbruegger** [comment]
Thanks for the Info. 
Like @cvdwl mentioned in issue #5 corona.help changed their Datasource.
I'm working on it!

**Comment by julianbruegger** [comment]
Titels
