### ISSUE TITLE
Syntax errors after fresh git pull

### ISSUE THREAD

**Issue by imhereyousee** [julianbruegger/corona-display#7]
pi@CoronaPi:~ $ git clone https://github.com/julianbruegger/corona-display.git
Cloning into 'corona-display'...
remote: Enumerating objects: 218, done.
remote: Counting objects: 100% (218/218), done.
remote: Compressing objects: 100% (147/147), done.
remote: Total 218 (delta 83), reused 185 (delta 59), pack-reused 0
Receiving objects: 100% (218/218), 2.17 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (83/83), done.
pi@CoronaPi:~ $ cd corona-display/
pi@CoronaPi:~/corona-display $ sudo chmod +x install.sh
pi@CoronaPi:~/corona-display $ sudo ./install.sh
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (2.21.0)
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.6).
git is already the newest version (1:2.20.1-2+deb10u1).
python-dev is already the newest version (2.7.16-1).
python-smbus is already the newest version (4.1-1).
python-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (0.7.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (4.7.1)
fatal: destination path 'Adafruit_Python_CharLCD' already exists and is not an empty directory.
running install
running bdist_egg
running egg_info
writing Adafruit_CharLCD.egg-info/PKG-INFO
writing dependency_links to Adafruit_CharLCD.egg-info/dependency_links.txt
writing requirements to Adafruit_CharLCD.egg-info/requires.txt
writing top-level names to Adafruit_CharLCD.egg-info/top_level.txt
reading manifest file 'Adafruit_CharLCD.egg-info/SOURCES.txt'
writing manifest file 'Adafruit_CharLCD.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/Adafruit_CharLCD
copying build/lib/Adafruit_CharLCD/Adafruit_CharLCD.py -> build/bdist.linux-armv7l/egg/Adafruit_CharLCD
copying build/lib/Adafruit_CharLCD/__init__.py -> build/bdist.linux-armv7l/egg/Adafruit_CharLCD
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_CharLCD/Adafruit_CharLCD.py to Adafruit_CharLCD.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/Adafruit_CharLCD/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_CharLCD.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_CharLCD.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_CharLCD.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_CharLCD.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying Adafruit_CharLCD.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/Adafruit_CharLCD-1.1.1-py3.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing Adafruit_CharLCD-1.1.1-py3.7.egg
Removing /usr/local/lib/python3.7/dist-packages/Adafruit_CharLCD-1.1.1-py3.7.egg
Copying Adafruit_CharLCD-1.1.1-py3.7.egg to /usr/local/lib/python3.7/dist-packages
Adafruit-CharLCD 1.1.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.7/dist-packages/Adafruit_CharLCD-1.1.1-py3.7.egg
Processing dependencies for Adafruit-CharLCD==1.1.1
Searching for Adafruit-GPIO==1.0.4
Best match: Adafruit-GPIO 1.0.4
Processing Adafruit_GPIO-1.0.4-py3.7.egg
Adafruit-GPIO 1.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/Adafruit_GPIO-1.0.4-py3.7.egg
Searching for spidev==3.4
Best match: spidev 3.4
Adding spidev 3.4 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Searching for Adafruit-PureIO==1.0.4
Best match: Adafruit-PureIO 1.0.4
Processing Adafruit_PureIO-1.0.4-py3.7.egg
Adafruit-PureIO 1.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/dist-packages/Adafruit_PureIO-1.0.4-py3.7.egg
Finished processing dependencies for Adafruit-CharLCD==1.1.1
pi@CoronaPi:~/corona-display $ sudo python3 display.py
  File "display.py", line 1
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
pi@CoronaPi:~/corona-display $

**Comment by probayraka** [comment]
Yeah. That happened to me too.

**Comment by julianbruegger** [comment]
Noted, I'm going to have a look!

**Comment by julianbruegger** [comment]
Looks like Adafruit made changes to their Library lately. 

> The examples in this guide are no longer supported. Check out the Character LCDs guide for CircuitPython and Python usage: https://learn.adafruit.com/character-lcds/python-circuitpython

- [ ] New wiring diagram
- [ ] Adjust code

**Comment by probayraka** [comment]
So Can you fix it?

**Comment by julianbruegger** [comment]
Looks like i'm going to work with an i2c lcd adapter.

**Comment by probayraka** [comment]
Oh noo

**Comment by julianbruegger** [comment]
Started with devlopment for an i2c Display.
[Branch](https://github.com/julianbruegger/corona-display/tree/i2c-display)

**Comment by julianbruegger** [comment]
New Version is up Now!
