### ISSUE TITLE
Country names like United States breaks fetch.py

### ISSUE THREAD

**Issue by Anstedt** [julianbruegger/corona-display#8]
If line 8 is changed to : url_c = "https://corona.help/country/us"

The following error occurs because the returned tuple is 'United' 'States' 'stats', 3 values.
File "fetch.py", line 27, in <module>
    first, last = country.split()
ValueError: too many values to unpack (expected 2)

A simple fix is to change:
first, last = country.split()
TO: which removes the last word, 'stats' from the name.
first = country.rsplit(' ',1)[0]

**Comment by julianbruegger** [comment]
You mean like metioned in the pul-request above (#9)?
